// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfPC5Zx7aAXt1u6Es3VFNI4fmvM5oWVyA',
    appId: '1:1000061938525:web:ea18fdac148bb8806f96b4',
    messagingSenderId: '1000061938525',
    projectId: 'botanicvisitguide',
    authDomain: 'botanicvisitguide.firebaseapp.com',
    storageBucket: 'botanicvisitguide.appspot.com',
    measurementId: 'G-WTWRCSJ55R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd0S8Wsfa4DFpv4Im9D-zK7NsLujtdL4E',
    appId: '1:1000061938525:android:88a78e52d5fbfde76f96b4',
    messagingSenderId: '1000061938525',
    projectId: 'botanicvisitguide',
    storageBucket: 'botanicvisitguide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcArlVNFqd71IRKeNAVO0C_NqTl3sPWMU',
    appId: '1:1000061938525:ios:a2b98ecd5fa9e97d6f96b4',
    messagingSenderId: '1000061938525',
    projectId: 'botanicvisitguide',
    storageBucket: 'botanicvisitguide.appspot.com',
    iosBundleId: 'com.example.botanicVisitGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcArlVNFqd71IRKeNAVO0C_NqTl3sPWMU',
    appId: '1:1000061938525:ios:537a3f3c4c816b176f96b4',
    messagingSenderId: '1000061938525',
    projectId: 'botanicvisitguide',
    storageBucket: 'botanicvisitguide.appspot.com',
    iosBundleId: 'com.example.botanicVisitGuide.RunnerTests',
  );
}
